# Generated by Django 5.2.17 on 2026-08-14 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('inspeccion', 'Inspección')], default='preventivo', max_length=20, verbose_name='tipo')),
                ('origin', models.CharField(choices=[('plan', 'Plan'), ('manual', 'Manual'), ('solicitud', 'Solicitud')], default='plan', max_length=20, verbose_name='origen')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('asignada', 'Asignada'), ('en_progreso', 'En progreso'), ('terminada', 'Terminada'), ('verificada', 'Verificada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='prioridad')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha programada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='terminada')),
                ('failure_description', models.TextField(blank=True, default='', verbose_name='descripción de la falla')),
                ('work_done', models.TextField(blank=True, default='', verbose_name='trabajo realizado')),
                ('downtime_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='tiempo de parada (min)')),
                ('labor_cost_cop', models.PositiveIntegerField(blank=True, null=True, verbose_name='mano de obra (COP)')),
                ('parts_cost_cop', models.PositiveIntegerField(blank=True, null=True, verbose_name='repuestos (COP)')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificada el')),
                ('cancel_reason', models.TextField(blank=True, default='', verbose_name='motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset', verbose_name='equipo')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='asignada a')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('plan', models.ForeignKey(blank=True, help_text='Vacío en las órdenes correctivas y manuales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.maintenanceplan', verbose_name='plan')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='verificada por')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
                'ordering': ['-due_date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['company'], name='workorders__company_e1e4dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'due_date'), name='workorder_unique_plan_due_date')],
            },
        ),
    ]
