# Generated by Django 5.2.17 on 2026-08-14 23:40

import apps.workorders.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        # The minimum this migration actually needs is the table its new FK
        # points at. makemigrations pinned the newest checklists migration
        # instead, which would have made this one unappliable without a
        # constraint it does not depend on.
        ('checklists', '0002_checklisttemplateitem_checklisttemplateitem_unique_template_order'),
        ('maintenance', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('text', models.CharField(max_length=500, verbose_name='texto')),
                ('item_type', models.CharField(choices=[('check', 'Check'), ('numeric', 'Numérico'), ('text', 'Texto')], default='check', max_length=10, verbose_name='tipo')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='unidad')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor máximo')),
                ('required', models.BooleanField(blank=True, default=True, verbose_name='obligatorio')),
                ('result', models.CharField(blank=True, choices=[('ok', 'OK'), ('falla', 'Falla'), ('na', 'N/A')], default='', max_length=10, verbose_name='resultado')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor medido')),
                ('note', models.TextField(blank=True, default='', verbose_name='observación')),
            ],
            options={
                'verbose_name': 'ítem de checklist de OT',
                'verbose_name_plural': 'ítems de checklist de OT',
                'ordering': ['work_order', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=255, upload_to=apps.workorders.storage.work_order_photo_upload_path, verbose_name='foto')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='descripción')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='tomada el')),
            ],
            options={
                'verbose_name': 'foto de OT',
                'verbose_name_plural': 'fotos de OT',
                'ordering': ['taken_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist_template',
            field=models.ForeignKey(blank=True, help_text='Versión exacta de la plantilla que se copió al crear la OT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='checklists.checklisttemplate', verbose_name='plantilla de checklist'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ejecutada por'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'due_date'], name='workorders__status_ff8862_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_to', 'status'], name='workorders__assigne_598c53_idx'),
        ),
        migrations.AddField(
            model_name='workorderchecklistitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='workorderchecklistitem',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workorders.workorder', verbose_name='OT'),
        ),
        migrations.AddField(
            model_name='workorderphoto',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='workorderphoto',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='tomada por'),
        ),
        migrations.AddField(
            model_name='workorderphoto',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workorders.workorder', verbose_name='OT'),
        ),
        migrations.AddIndex(
            model_name='workorderchecklistitem',
            index=models.Index(fields=['company'], name='workorders__company_7d0843_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderchecklistitem',
            constraint=models.UniqueConstraint(fields=('work_order', 'order'), name='workorderchecklistitem_unique_wo_order'),
        ),
        migrations.AddIndex(
            model_name='workorderphoto',
            index=models.Index(fields=['company'], name='workorders__company_1035bb_idx'),
        ),
    ]
