# Generated by Django 5.2.17 on 2026-08-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('workorders', '0002_workorderchecklistitem_workorderphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='source_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='requests.maintenancerequest', verbose_name='solicitud de origen'),
        ),
    ]
