# Generated by Django 5.2.17 on 2026-08-15 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        ('checklists', '0003_checklisttemplate_checklisttemplate_unique_parent'),
        ('maintenance', '0001_initial'),
        ('requests', '0001_initial'),
        ('workorders', '0003_workorder_source_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['company', 'finished_at'], name='workorder_company_finished'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['company', 'due_date'], name='workorder_company_due'),
        ),
    ]
