# Generated by Django 5.2.17 on 2026-08-15 19:13

import apps.requests_.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='¿Qué está fallando?')),
                ('photo', models.FileField(blank=True, help_text='Opcional. Una foto de la falla ahorra un viaje.', max_length=255, upload_to=apps.requests_.storage.request_photo_upload_path, verbose_name='foto')),
                ('status', models.CharField(choices=[('nueva', 'Nueva'), ('convertida', 'Convertida'), ('rechazada', 'Rechazada')], default='nueva', max_length=20, verbose_name='estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada el')),
                ('review_note', models.TextField(blank=True, default='', max_length=2000, verbose_name='motivo del rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reportada el')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='assets.asset', verbose_name='equipo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='reportada por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'solicitud de mantenimiento',
                'verbose_name_plural': 'solicitudes de mantenimiento',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['company'], name='requests_ma_company_721a87_idx'), models.Index(fields=['status', '-created_at'], name='requests_ma_status_9bb855_idx'), models.Index(fields=['reported_by', '-created_at'], name='requests_ma_reporte_d02c9f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'rechazada'), _negated=True), models.Q(('review_note', ''), _negated=True), _connector='OR'), name='maintenancerequest_rejection_needs_a_note')],
            },
        ),
    ]
