# Generated by Django 5.2.17 on 2026-08-14 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='assets.assetcategory', verbose_name='categoría')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='checklists.checklisttemplate', verbose_name='versión anterior')),
            ],
            options={
                'ordering': ['name', '-version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('text', models.CharField(max_length=500, verbose_name='texto')),
                ('item_type', models.CharField(choices=[('check', 'Check'), ('numeric', 'Numérico'), ('text', 'Texto')], default='check', max_length=10, verbose_name='tipo')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='unidad')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor máximo')),
                ('required', models.BooleanField(blank=True, default=True, verbose_name='obligatorio')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='plantilla')),
            ],
            options={
                'ordering': ['template', 'order'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['company'], name='checklists__company_6cdd30_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplateitem',
            index=models.Index(fields=['company'], name='checklists__company_3899dc_idx'),
        ),
    ]
