# Generated by Django 5.2.17 on 2026-08-14 04:40

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checklisttemplateitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('template', 'order'), name='checklisttemplateitem_unique_template_order'),
        ),
    ]
