# Generated by Django 5.2.17 on 2026-08-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        ('checklists', '0002_checklisttemplateitem_checklisttemplateitem_unique_template_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent',), name='checklisttemplate_unique_parent'),
        ),
    ]
