# Generated by Django 5.2.17 on 2026-08-14 16:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        ('checklists', '0002_checklisttemplateitem_checklisttemplateitem_unique_template_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('preventivo', 'Preventivo'), ('inspeccion', 'Inspección'), ('lubricacion', 'Lubricación'), ('calibracion', 'Calibración')], default='preventivo', max_length=20, verbose_name='tipo')),
                ('frequency_type', models.CharField(choices=[('calendar', 'Por calendario'), ('meter', 'Por horómetro')], default='calendar', max_length=10, verbose_name='frecuencia')),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cada cuántos días')),
                ('meter_interval_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cada cuántas horas')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='próximo vencimiento')),
                ('hours_at_last_generated_wo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='horómetro de la última OT generada')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duración estimada (min)')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='assets.asset', verbose_name='equipo')),
                ('checklist_template', models.ForeignKey(blank=True, help_text='Al crear cada OT se usa la última versión activa de esta plantilla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='checklists.checklisttemplate', verbose_name='plantilla de checklist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable por defecto')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['company'], name='maintenance_company_15ffee_idx'), models.Index(fields=['next_due_date'], name='maintenance_next_du_b64446_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('frequency_type', 'calendar'), ('interval_days__isnull', False), ('next_due_date__isnull', False)), models.Q(('frequency_type', 'meter'), ('meter_interval_hours__isnull', False)), _connector='OR'), name='maintenanceplan_frequency_fields_required', violation_error_message='Falta la frecuencia del plan: indica los días y el próximo vencimiento (calendario) o las horas (horómetro).'), models.CheckConstraint(condition=models.Q(('interval_days__isnull', True), ('interval_days__gte', 1), _connector='OR'), name='maintenanceplan_interval_days_positive', violation_error_message='El intervalo en días debe ser de al menos 1.'), models.CheckConstraint(condition=models.Q(('meter_interval_hours__isnull', True), ('meter_interval_hours__gt', 0), _connector='OR'), name='maintenanceplan_meter_interval_positive', violation_error_message='El intervalo en horas debe ser mayor que cero.')],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_hours', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='horómetro (h)')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de lectura')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('work_order', 'Orden de trabajo')], default='manual', max_length=20, verbose_name='origen')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='assets.asset', verbose_name='equipo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'lectura de horómetro',
                'verbose_name_plural': 'lecturas de horómetro',
                'ordering': ['-read_at', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['company'], name='maintenance_company_aae9b5_idx'), models.Index(fields=['asset', '-read_at'], name='maintenance_asset_i_6181c7_idx')],
            },
        ),
    ]
