# Generated by Django 5.2.17 on 2026-08-14 00:25

import apps.assets.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Etiqueta interna del equipo.', max_length=50, verbose_name='código')),
                ('qr_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='marca')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='número de serie')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='garantía hasta')),
                ('criticality', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='criticidad')),
                ('status', models.CharField(choices=[('operativo', 'Operativo'), ('detenido', 'Detenido'), ('dado_de_baja', 'Dado de baja')], default='operativo', max_length=20, verbose_name='estado')),
                ('location_detail', models.CharField(blank=True, default='', max_length=200, verbose_name='ubicación específica')),
                ('main_photo', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.assets.storage.asset_photo_upload_path, verbose_name='foto principal')),
                ('specs', models.JSONField(blank=True, default=list, help_text="Lista ordenada de pares clave-valor: [{'key': ..., 'value': ...}].", verbose_name='ficha técnica')),
                ('baja_reason', models.TextField(blank=True, default='', verbose_name='motivo de baja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounts.site', verbose_name='sitio')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='categoría')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('garantia', 'Garantía'), ('certificado', 'Certificado'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='tipo')),
                ('file', models.FileField(max_length=255, upload_to=apps.assets.storage.asset_document_upload_path, verbose_name='archivo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['company'], name='assets_asse_company_acb54b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='assetcategory_unique_company_name'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company'], name='assets_asse_company_492af9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['qr_uuid'], name='assets_asse_qr_uuid_c58492_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='asset_unique_company_code'),
        ),
        migrations.AddIndex(
            model_name='assetdocument',
            index=models.Index(fields=['company'], name='assets_asse_company_ff3202_idx'),
        ),
    ]
