# Generated by Django 5.2.17 on 2026-08-15 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=150, verbose_name='usuario (nombre)')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Edición'), ('delete', 'Eliminación'), ('transition', 'Cambio de estado'), ('send', 'Envío')], max_length=20, verbose_name='acción')),
                ('model_label', models.CharField(max_length=60, verbose_name='modelo')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='id del objeto')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='objeto')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, help_text='Vacío solo cuando la acción la ejecuta el sistema (el programador).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['company'], name='audit_audit_company_6a2373_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['model_label', 'object_id'], name='audit_audit_model_l_b619eb_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx')],
            },
        ),
    ]
