# Generated by Django 5.2.17 on 2026-08-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('assets', '0001_initial'),
        ('workorders', '0002_workorderchecklistitem_workorderphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Correo')], default='email', max_length=20, verbose_name='canal')),
                ('kind', models.CharField(choices=[('hoja_de_vida', 'Hoja de vida'), ('informe_ot', 'Informe de OT'), ('credenciales', 'Contraseña temporal')], max_length=20, verbose_name='tipo')),
                ('recipient', models.CharField(max_length=254, verbose_name='destinatario')),
                ('subject', models.CharField(max_length=255, verbose_name='asunto')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20, verbose_name='estado')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name='detalle del error')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='assets.asset', verbose_name='equipo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workorders.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'envío',
                'verbose_name_plural': 'envíos',
                'ordering': ['-sent_at', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['company'], name='reports_not_company_d9643a_idx'), models.Index(fields=['-sent_at'], name='reports_not_sent_at_521dea_idx')],
            },
        ),
    ]
